
name: 'hubspot_integration_tests'
version: '0.3.2'
profile: 'integration_tests'
config-version: 2

models:
  hubspot:
    +materialized: view

vars:
  hubspot_source:
    hubspot_database: raw
    hubspot_schema: raw_fivetran_hubspot
