
name: 'hubspot_integration_tests'
version: '0.3.2'
profile: 'integration_tests'
config-version: 2

clean-targets:
  - 'target'
  - 'dbt_modules'
  - 'logs'

vars:
  hubspot:
    hubspot_email_event_enabled: false
    hubspot_engagement_enabled: false
    hubspot_service_enabled: false
  hubspot_source:
    hubspot_database: raw
    hubspot_schema: raw_fivetran_hubspot
    hubspot_email_event_enabled: false
    hubspot_engagement_enabled: false
    hubspot_service_enabled: false
